### ISSUE TITLE
PSA:  How to disable the "Fill Screen" Feature

### ISSUE THREAD

**Issue by dougwells** [stuyam/CSSDevices#8]
Stuart - You are a genius!  CSSDevices rocks!  If you'd like, I am happy to build a separate class for this and make a pull request.  Let me know.  Also, if there is a better solution please let me & the community know.  Again ... I think CSSDevices is pure genius.  Well done.

All - I spent a few hours figuring out how to disable the "Fill Screen" issue.  Thought I would share it with others.  Pretty simple fix once I found it.  Currently line 545 of the devices.css file.  Simply change the fields as shown below.  Hope this proves helpful.

`.cd-screen > * {
  display: inline-block; /* originally was "none" */
  position: static;  /* originally was "absolute" */
  /*top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 100%;*/
  color: white;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  -o-user-select: none;
  user-select: none;
  -webkit-user-drag: none;
  -moz-user-drag: none;
  user-drag: none; }`

**Comment by yamartino** [comment]
Thanks @dougwells! Really appreciate all of the positive feedback. Just so I can understand what it is that you are trying to accomplish, can you explain what you want then end result of this to be? What element are you trying to put inside the screen and what do you want it to look like? Include screenshots if you can, that would be super helpful. Thanks for bringing this to my attention :smile:
